package dao;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import model.Player;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public class PlayerRepository extends RepositoryBase<Player> implements IPlayerRepository {
	
	public PlayerRepository(Connection connection, IMapResultSetIntoEntity<Player> mapper, IUnitOfWork uow) {
		super(connection, mapper, uow);
	}
	
	@Override
	protected String tableName() {
		return "player";
	}
	
	@Override
	protected String createTableSql() {
		return "CREATE TABLE player("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "age INT,"
				+ "country VARCHAR(20),"
				+ "team VARCHAR(20),"
				+ "experience INT,"
				+ "playerStatistics INT,"
				+ "teamId INT"
				+ ")";
	}
	
	@Override
	protected String insertSql() {
		return "INSERT INTO player(name,age,country,team,experience,playerStatistics,teamId) VALUES(?,?,?,?,?,?,?)";
	}
	
	@Override
	protected String deleteSql() {
		return "DELETE FROM player WHERE id = ?";
	}
	
	@Override
	protected String updateSql() {
		return "UPDATE player set name=?, age=?, country=?, team=?, experience=?, playerStatistics=?, teamId=? WHERE id=?";
	}
	
	@Override
	protected String selectByIdSql() {
		return "SELECT * FROM player WHERE id=?";
	}

	@Override
	protected String selectAllSql() {
		return "SELECT * FROM player";
	}
	
	@Override
	protected void setupInsert(Player entity) throws SQLException {
		insert.setString(1, entity.getName());
		insert.setInt(2, entity.getAge());
		insert.setString(3, entity.getCountry());
		insert.setString(4, entity.getTeam());
		insert.setInt(5, entity.getExperience());
		insert.setInt(6, entity.getPlayerStatistics());
		insert.setInt(7, entity.getTeamId());
	}
	
	@Override
	protected void setupUpdate(Player entity) throws SQLException {
		update.setString(1, entity.getName());
		update.setInt(2, entity.getAge());
		update.setString(3, entity.getCountry());
		update.setString(4, entity.getTeam());
		update.setInt(5, entity.getExperience());
		update.setInt(6, entity.getPlayerStatistics());
		update.setInt(7, entity.getTeamId());
		update.setInt(8, entity.getId());	
	}
	
	public List<Player> byTeam(String name) {
		return null;
	}
}
